### ISSUE TITLE
ReadHistoryRequest doesn't mark messages as read

### ISSUE THREAD

**Issue by xates** [xates/tg-channel-dumper#1]

**Comment by SyrianProgrammer** [comment]
i am use script tg-channel-dumper 
ReadHistoryRequest doesn't mark messages as read

**Comment by xates** [comment]
Yeah, that's the matter of the issue...
I could't figure out why that happens, so if you manage to find out why, you are welcome to let me know here, or to make a pull request.

**Comment by SyrianProgrammer** [comment]
to mark read messages from channels only.
```
from telethon.tl.functions.channels import ReadHistoryRequest

channel = client.get_entity(message.message.to_id)
client(ReadHistoryRequest(channel=channel, max_id=message.message.id))
```

**Comment by SyrianProgrammer** [comment]
if you want Increasing View Count messages from channels:

https://github.com/LonamiWebs/Telethon/wiki/Increasing-View-Count

**Comment by xates** [comment]
Yeah, that's exactly how I do it if you read the code. But it doesn't work
I read the wiki section about how to increase view count in channels too, but I'm not interested in that.

**Comment by SyrianProgrammer** [comment]
to increase view count in channels:
```
from telethon.tl.functions.channels import GetMessagesViewsRequest

channel = client.get_entity(message.message.to_id)
client(GetMessagesViewsRequest(peer=channel, id=[message.message.id], increment=True))
```

**Comment by xates** [comment]
Not sure if you understand what I am saying here... it just seems you are copy-pasting the same thing again and again...

Anyway I have fixed it. It was caused by the import of `telethon.tl.functions.messages`, which contains a constructor named `ReadHistoryRequest` too, which is used for user messages and overrode the `telethon.tl.functions.messages.ReadHistoryRequest` I needed.
